[SupersonicTheme]
Name = "noctalia"
Version = "0.1"
SupportsDark = true
SupportsLight = true


[LightColors]
PageBackground = "{{colors.background.light.hex}}ff"
ListHeader = "{{colors.on_primary.light.hex}}ff"
PageHeader = "{{colors.surface_dim.light.hex}}ff"
Background = "{{colors.on_primary.light.hex}}ff"
Button = "{{colors.surface_dim.light.hex}}ff"
DisabledButton = "{{colors.surface_variant.light.hex}}ff"
Disabled = "{{colors.on_background.light.hex}}ff"
Error = "{{colors.error.light.hex}}ff"
Focus = "{{colors.surface_bright.light.hex}}ff"
Foreground = "{{colors.on_surface.light.hex}}ff"
ForegroundOnError = "{{colors.surface.light.hex}}ff"
ForegroundOnPrimary = "{{colors.surface.light.hex}}ff"
ForegroundOnSuccess = "{{colors.surface.light.hex}}ff"
ForegroundOnWarning = "{{colors.surface.light.hex}}ff"
HeaderBackground = "{{colors.surface_variant.light.hex}}ff"
Hover = "{{colors.surface_container_low.light.hex}}ff"
Hyperlink = "{{colors.primary.light.hex}}ff"
InputBackground = "{{colors.surface_dim.light.hex}}ff"
InputBorder = "{{colors.surface_variant.light.hex}}ff"
MenuBackground = "{{colors.surface_dim.light.hex}}ff"
OverlayBackground = "{{colors.surface_dim.light.hex}}ff"
Placeholder = "{{colors.outline.light.hex}}ff"
Pressed = "{{colors.surface_variant.light.hex}}66"
Primary = "{{colors.primary.light.hex}}ff"
ScrollBar = "{{colors.surface_dim.light.hex}}99"
Selection = "{{colors.inverse_primary.light.hex}}99"
Separator = "{{colors.on_primary.light.hex}}ff"
Success = "{{colors.tertiary.light.hex}}ff"
Warning = "{{colors.secondary_fixed.light.hex}}ff"


[DarkColors]
PageBackground = "{{colors.background.dark.hex}}ff"
ListHeader = "{{colors.on_primary.dark.hex}}ff"
PageHeader = "{{colors.surface_dim.dark.hex}}ff"
Background = "{{colors.on_primary.dark.hex}}ff"
Button = "{{colors.surface_dim.dark.hex}}ff"
DisabledButton = "{{colors.surface_variant.dark.hex}}ff"
Disabled = "{{colors.on_background.dark.hex}}ff"
Error = "{{colors.error.dark.hex}}ff"
Focus = "{{colors.surface_bright.dark.hex}}ff"
Foreground = "{{colors.on_surface.dark.hex}}ff"
ForegroundOnError = "{{colors.surface.dark.hex}}ff"
ForegroundOnPrimary = "{{colors.surface.dark.hex}}ff"
ForegroundOnSuccess = "{{colors.surface.dark.hex}}ff"
ForegroundOnWarning = "{{colors.surface.dark.hex}}ff"
HeaderBackground = "{{colors.surface_variant.dark.hex}}ff"
Hover = "{{colors.surface_container_low.dark.hex}}ff"
Hyperlink = "{{colors.primary.dark.hex}}ff"
InputBackground = "{{colors.surface_dim.dark.hex}}ff"
InputBorder = "{{colors.surface_variant.dark.hex}}ff"
MenuBackground = "{{colors.surface_dim.dark.hex}}ff"
OverlayBackground = "{{colors.surface_dim.dark.hex}}ff"
Placeholder = "{{colors.outline.dark.hex}}ff"
Pressed = "{{colors.surface_variant.dark.hex}}66"
Primary = "{{colors.primary.dark.hex}}ff"
ScrollBar = "{{colors.surface_dim.dark.hex}}99"
Selection = "{{colors.inverse_primary.dark.hex}}99"
Separator = "{{colors.on_primary.dark.hex}}ff"
Success = "{{colors.tertiary.dark.hex}}ff"
Warning = "{{colors.secondary_fixed.dark.hex}}ff"
