---
# To get a new key from remote SSH machine, invoke:
# nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'

keys:
  - users:
      - &ajgon age13s2dafyr9sfltp8heujttxug4v4m3qhj7sxzqrj6x6x3cu5n29uqfvj62l
  - hosts:
      - &deedee age15j2q7j9nx0eklslk93zstedzkhhm3r6kqfd7pgcesne6c9yeldzqdvm0v8
      - &leelee age1f2dmyxwyn9gy75ccpk27yaax4ce7nu2nua4muwuk2rrtt7nm33yqe9zzrj
      - &meemee age1jvlrjcy0fh4tspzv5z4cxulmhrd5c5htkd8juuxpmn3vnk3xtsdqeggxhg

creation_rules:
  - path_regex: local/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
  - path_regex: deedee/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
          - *deedee
  - path_regex: leelee/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
          - *leelee
  - path_regex: meemee/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
          - *meemee

  # desktops
  - path_regex: dexter/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
  - path_regex: liadtop/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
