---
# To get a new key from remote SSH machine, invoke:
# nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
keys:
  - users:
      - &ajgon ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOrBLT88ZZ+lO8hHcj+4jqtor79OLhQZcDWF98kkWkfn
      - &homeManager age13lpwsgyvdsu690mg4kup99cuzmtq8kwu0t9zmj5ufkshvacxpecsyfmzlv
  - hosts:
      - &dexter age1s3hlmga37ylfxp7y96uha27j6g4mxjs74ecsvjs9d6hwrv0uus5s4teuqn
      - &liadtop age1czs2uzrun89mfzaykc2cl65auktzdhkky9lgp7c28wf6ezzz34sq5zhl6q
      - &work age1p3frxma9rmdfxf4dd26yyc3q9an667k99za5sqyl6ma7e206wdcs7k3ja5
creation_rules:
  - path_regex: home/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
          - *homeManager
  - path_regex: dexter/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
          - *dexter
  - path_regex: liadtop/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
          - *liadtop
  - path_regex: work/.*\.sops\.yaml$
    key_groups:
      - age:
          - *ajgon
          - *work
