---
# yaml-language-server: disabled
theme: dark
default_2fa_method: 'webauthn'
server:
  address: "tcp://0.0.0.0:9091"
  asset_path: ''
  disable_healthcheck: true
  headers:
    csp_template: ''
  buffers:
    read: 8192
    write: 8192
  timeouts:
    read: 6s
    write: 6s
    idle: 30s
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz:
      auth-request:
        implementation: "AuthRequest"
        authn_strategies:
          - name: 'HeaderAuthRequestProxyAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'

log:
  level: info
  format: text
  file_path: ''
  keep_stdout: true
telemetry:
  metrics:
    enabled: true
    address: "tcp://0.0.0.0:9959"
    buffers:
      read: 4096
      write: 4096
totp:
  disable: false
  issuer: "{{ROOT_DOMAIN}}"
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  selection_criteria:
    user_verification: preferred
  timeout: 60s
ntp:
  disable_startup_check: true
authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 0
session:
  name: 'authelia_session'
  same_site: 'lax'
  expiration: 18h
  inactivity: 4h
  remember_me: 10y
  cookies:
    - domain: "{{ROOT_DOMAIN}}"
      authelia_url: "https://authelia.{{ROOT_DOMAIN}}"
      default_redirection_url: 'https://www.{{ROOT_DOMAIN}}/'
  redis:
    host: host.docker.internal
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
regulation:
  ban_time: 5m
  find_time: 2m
  max_retries: 3
storage:
  postgres:
    schema: public
    timeout: 5s
notifier:
  disable_startup_check: false
  smtp:
    address: "smtp://maddy:25"
    timeout: 5s
    sender: "{{NOTIFICATION_SENDER}}"
    identifier: "{{ROOT_DOMAIN}}"
    subject: '[Authelia] {title}'
    startup_check_address: "{{NOTIFICATION_SENDER}}"
    disable_html_emails: false
    disable_require_tls: true
    disable_starttls: false
identity_providers:
  oidc:
    enforce_pkce: public_clients_only
    enable_pkce_plain_challenge: false
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    cors:
      allowed_origins_from_client_redirect_uris: true
    clients: []
    # yamllint disable
    jwks:
      - key: "@@AUTHELIA_IDENTITY_PROVIDERS_OIDC_JWKS_KEY@@"
    # yamllint enable
    lifespans:
      access_token: 1h
      authorize_code: 1m
      id_token: 1h
      refresh_token: 90m
access_control:
  default_policy: two_factor
...
