_: {
  flake.homeModules.features-home-dosbox =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    let
      cfg = config.features.home.dosbox;
      dosboxPkg = pkgs.writeShellApplication {
        name = "dosbox-x";
        runtimeInputs = with pkgs; [
          coreutils # mktemp, readlink, mkdir, rm, sleep, sort
          dosbox-x
          findutils # find
          unzip
        ];

        text = ''
          SAVEPATH="${cfg.savePath}"

          mkdir -p -- "$SAVEPATH"
          savepath=$(readlink -f -- "$SAVEPATH")

          workdir=$(mktemp -d "''${TMPDIR:-/tmp}/dosbox-x-conf.XXXXXXXXXX")

          # shellcheck disable=SC2329  # invoked from a trap
          cleanup() {
            if [ -n "''${workdir:-}" ]; then
              rm -rf -- "$workdir"
            fi
          }

          # shellcheck disable=SC2329  # invoked from a trap
          terminate() {
            local sig=$1 status=$2 i
            if [ -n "''${dosbox_pid:-}" ]; then
              kill -s "$sig" "$dosbox_pid" 2>/dev/null || true
              for ((i = 0; i < 20; i++)); do
                kill -0 "$dosbox_pid" 2>/dev/null || break
                sleep 0.25
              done
              if kill -0 "$dosbox_pid" 2>/dev/null; then
                kill -s TERM "$dosbox_pid" 2>/dev/null || true
              fi
              wait "$dosbox_pid" 2>/dev/null || true
            fi
            exit "$status"
          }

          trap 'rc=$?; cleanup; exit "$rc"' EXIT
          trap 'terminate INT 130' INT
          trap 'terminate TERM 143' TERM
          trap 'terminate HUP 129' HUP

          is_archive() {
            local arg=$1
            [ -f "$arg" ] || return 1
            case "''${arg,,}" in
              *.zip | *.7z) return 0 ;;
              *) return 1 ;;
            esac
          }

          archives=()
          for arg in "$@"; do
            is_archive "$arg" || continue
            archives+=("$arg")
          done

          if [ "''${#archives[@]}" -gt 1 ]; then
            printf 'dosbox-x: only one archive may be given, got %d:\n' "''${#archives[@]}" >&2
            printf '  %s\n' "''${archives[@]}" >&2
            exit 2
          fi

          args=(-conf "${config.xdg.configHome}/dosbox-x/dosbox-x.conf")

          if [ "''${#archives[@]}" -eq 1 ]; then
            zipfile=''${archives[0]}
            target="$workdir/zip"
            mkdir -p -- "$target"

            case "''${zipfile,,}" in
              *.7z)
                printf 'dosbox-x: cannot extract configs from 7z archive: %s\n' "$zipfile" >&2
                ;;
              *)
                unzip_rc=0
                unzip -q -C -o -- "$zipfile" '*.conf' -d "$target" || unzip_rc=$?
                case $unzip_rc in
                  0 | 11) ;;
                  *)
                    printf 'dosbox-x: unzip failed on %s (exit %d)\n' "$zipfile" "$unzip_rc" >&2
                    exit "$unzip_rc"
                    ;;
                esac
                ;;
            esac

            zipname=$(basename -- "$zipfile")
            overlay_dir="$savepath/''${zipname%.*}"
            mkdir -p -- "$overlay_dir"

            alphabet='abcdefghijklmnopqrstuvwxyz0123456789'
            overlay_conf=
            while :; do
              candidate=
              for ((i = 0; i < 16; i++)); do
                candidate+="''${alphabet:RANDOM%''${#alphabet}:1}"
              done
              if [ -z "$(find "$workdir" -name "$candidate.conf" -print -quit)" ]; then
                overlay_conf="$workdir/$candidate.conf"
                break
              fi
            done

            printf '%s\n' \
              '# generated by dosbox-x.nix -- redirect writes to C: into the save dir' \
              '[autoexec]' \
              "mount c \"$overlay_dir\" -t overlay" \
              >"$overlay_conf"

            game_confs=()
            while IFS= read -r -d ${"''"} conf; do
              game_confs+=("$conf")
            done < <(
              find "$workdir" -mindepth 2 -type f -name '*.conf' -print0 | LC_ALL=C sort -z
            )

            args+=(-prerun -conf "$overlay_conf")
            for conf in "''${game_confs[@]}"; do
              args+=(-conf "$conf")
            done
          fi

          dosbox-x "''${args[@]}" "$@" &
          dosbox_pid=$!

          rc=0
          wait "$dosbox_pid" || rc=$?
          exit "$rc"
        '';

        meta = {
          description = "dosbox-x wrapper that redirects writes to ZIP-mounted games into a save directory";
          mainProgram = "dosbox-x";
        };
      };
    in
    {
      options.features.home.dosbox = {
        savePath = lib.mkOption {
          type = lib.types.path;
          description = "Path to saves directory.";
          default = "${config.xdg.stateHome}/dosbox-x/save";
        };
      };
      config = {
        home = {
          packages = [ dosboxPkg ];
          shellAliases.dosbox = lib.getExe dosboxPkg;
        };

        xdg.configFile = {
          "dosbox-x/dosbox-x.conf".text = ''
            [sdl]
            maximize = true

            [dosbox]
            saveremark   = false
            quit warning = false
          '';
        };
      };
    };
}
