---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Populate cache
'on':
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ forgejo.ref }}-${{ forgejo.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    runs-on: nix
    environment: production
    steps:
      - name: Checkout
        run: |
          git init -b master
          git remote add origin \
          "http://x-access-token:${FORGEJO_TOKEN}@${FORGEJO_SERVER_URL#http*://}/${FORGEJO_REPOSITORY}.git"
          git fetch --depth=1 origin "${FORGEJO_REF_NAME}"
          git checkout FETCH_HEAD

          nix-env -iA gnused -f '<nixpkgs>' || true
          sed -i'' 's@enable: true@enable: false@g' devenv.yaml

      - name: Build and push to cache
        run: |-
          mkdir -p ~/.config/nix
          echo 'experimental-features = nix-command flakes' > ~/.config/nix/nix.conf

          nix --accept-flake-config run .#cache -- \
          --ci --attic-token='${{ secrets.ATTIC_TOKEN }}' --github-token='${{ secrets.GH_TOKEN }}'
        env:
          CI: "true"
