_: {
  imports = [
    ./audiobookshelf
    ./atuin
    ./authelia
    ./bazarr
    ./beszel
    ./bitmagnet
    ./borgmatic
    ./caddy
    ./calibre-web-automated
    ./coredns
    ./crypt
    ./echo-server
    ./davis
    ./filebrowser
    ./firefly-iii
    ./firefoxsync
    ./flaresolverr
    ./forgejo
    ./gatus
    ./gluetun
    ./gose
    ./home-assistant
    ./homepage
    ./immich
    ./jellyfin
    ./kms
    ./koreader
    ./lldap
    ./maddy
    ./mail-archive
    ./matchbox
    ./memos
    ./miniflux
    ./minio
    ./navidrome
    ./netbox
    ./open-webui
    ./outline
    ./paperless-ngx
    ./pinchflat
    ./piped
    ./prowlarr
    ./qbittorrent
    ./radarr
    ./recyclarr
    ./redlib
    ./registry
    ./retrom
    ./sonarr
    ./sshwifty
    ./syncthing
    ./talos-factory
    ./tftpd
    ./tika
    ./upsnap
    ./vaultwarden
    ./vikunja
    ./wakapi
    ./wallos
    ./wg-easy
    ./whoogle
    ./zigbee2mqtt
  ];
}
